name: OrangeFox Recovery Builder 2024

on:
  workflow_dispatch:
    inputs:
      DEVICE_CODENAME:
        description: 'Device codename'
        required: true
        default: 'beyond2lte'
      DEVICE_TREE_URL:
        description: 'Device tree GitHub URL'
        required: true
        default: 'https://github.com/iHagoss/android_device_samsung_beyond2lte'
      DEVICE_TREE_BRANCH:
        description: 'Branch for your device tree'
        required: true
        default: 'extreme-a14'
      FOX_BRANCH:
        description: 'OrangeFox branch'
        required: true
        default: 'fox_12.1'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib \
        gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev \
        lib32z1-dev liblz4-tool libncurses5-dev libssl-dev libxml2-utils lzop \
        openjdk-11-jdk pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

    - name: Sync OrangeFox sources
      run: |
        mkdir -p ~/orangefox && cd ~/orangefox
        git clone https://gitlab.com/OrangeFox/sync.git
        cd sync
        ./orangefox_sync.sh --branch ${{ github.event.inputs.FOX_BRANCH }} \
          --path ../fox_${{ github.event.inputs.FOX_BRANCH }}

    - name: Clone your device tree
      run: |
        cd ~/orangefox/fox_${{ github.event.inputs.FOX_BRANCH }}
        git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} device/samsung/${{ github.event.inputs.DEVICE_CODENAME }}

    - name: Build recovery.img
      run: |
        cd ~/orangefox/fox_${{ github.event.inputs.FOX_BRANCH }}
        source build/envsetup.sh
        lunch twrp_${{ github.event.inputs.DEVICE_CODENAME }}-eng
        mka recoveryimage -j$(nproc)

    - name: Upload recovery.img to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ~/orangefox/fox_${{ github.event.inputs.FOX_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_CODENAME }}/recovery.img
        tag_name: OrangeFox-${{ github.run_number }}
        name: OrangeFox Build ${{ github.run_number }}
        body: |
          OrangeFox Recovery for ${{ github.event.inputs.DEVICE_CODENAME }}
          Branch: ${{ github.event.inputs.FOX_BRANCH }}
          Tree: ${{ github.event.inputs.DEVICE_TREE_URL }} @ ${{ github.event.inputs.DEVICE_TREE_BRANCH }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
