name: Build OrangeFox Recovery - Beyond2lte

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y git wget repo python3 unzip bc cpio build-essential \
          gcc g++ make libncurses5-dev libssl-dev flex bison curl zlib1g-dev \
          openjdk-8-jdk android-sdk-libsparse-utils rsync

    - name: Create working directories
      run: |
        mkdir -p ~/orangefox
        cd ~/orangefox

    - name: Initialize OrangeFox source
      run: |
        cd ~/orangefox
        repo init -u https://gitlab.com/OrangeFox/manifest.git -b fox_12.1
        repo sync -j$(nproc) --force-sync

    - name: Clone device tree
      run: |
        cd ~/orangefox
        git clone https://github.com/iHagoss/android_device_samsung_beyond2lte.git device/samsung/beyond2lte

    - name: Set up environment variables
      run: |
        echo "export ALLOW_MISSING_DEPENDENCIES=true" >> ~/.bashrc
        echo "export FOX_USE_BASH_SHELL=1" >> ~/.bashrc
        echo "export LC_ALL=C" >> ~/.bashrc
        echo "export OF_SCREEN_H=2280" >> ~/.bashrc
        echo "export OF_STATUS_H=80" >> ~/.bashrc
        echo "export OF_STATUS_INDENT_LEFT=48" >> ~/.bashrc
        echo "export OF_STATUS_INDENT_RIGHT=48" >> ~/.bashrc
        echo "export FOX_VIRTUAL_AB_DEVICE=1" >> ~/.bashrc
        echo "export OF_AB_DEVICE_WITH_RECOVERY_PARTITION=1" >> ~/.bashrc
        echo "export OF_USE_MAGISKBOOT=1" >> ~/.bashrc
        echo "export FOX_BUILD_DEVICE=beyond2lte" >> ~/.bashrc
        echo "export FOX_TARGET_PACKAGE=OrangeFox-beyond2lte.img" >> ~/.bashrc
        source ~/.bashrc

    - name: Build OrangeFox
      run: |
        cd ~/orangefox
        . build/envsetup.sh
        lunch omni_beyond2lte-eng
        mka recoveryimage

    - name: Upload recovery image
      uses: actions/upload-artifact@v3
      with:
        name: OrangeFox-beyond2lte
        path: ~/orangefox/out/target/product/beyond2lte/recovery.img
